bot:
  token: "bot-token"
  defaultLanguage: "tr"
  developers:
    - "dev-id"
commands:
  defaultPrefix: ">"
  registerOnStart: false # Optional, set true to register slash commands on start
